### PR TITLE
Rename some to 'tx' to 'transaction'

### PR DESCRIPTION
**Pull request by delaaxe**
Trying to match Starkware's code quality before mainnet launch

### CODE REVIEW

**Comment by seanjameshan** [comment]
Been trying to merge this but tests been failing. I think it's because the starknet network is down. Going to keep re-running the test case to see if it passes.

**Comment by janek26** [comment]
this needs a rebase from develop to pass tests.
I'd consider this a major release if it changes external methods

**Comment by delaaxe** [comment]
No methods are changed in this PR but if we're going to do a major, might as well rename the `waitForTx` method

**Comment by seanjameshan** [comment]
@delaaxe can you try rebasing dev and see if tests pass? I can also take a look end of week. Like you said no methods are changed with this PR.

**Pull request merged**
