### PR TITLE
Specifying custom nonces

### PR DESCRIPTION
**Pull request by vixidev99**
When sending multiple transactions at once, the chain state does not update fast enough to reveal an updated nonce, so transactions get signed with the same nonce and rejected. 

This feature allows passing a custom nonce to a transaction so that users can manually input nonces to push transactions through.

### CODE REVIEW

**Comment by seanjameshan** [comment]
@vixidev99 Thanks a lot for the PR. 

Could you merge this to `develop` first?  I think @delaaxe may have merged the transaction renaming which could have a conflict.

@janek26 could you take a look at this as well? It looks good to me but would like your eyes on it as you've implemented the signer

**Comment by delaaxe** [comment]
@seanjameshan I didn't merge the PR in question but I can still help if there are any conflict issues!

**Comment by janek26** [comment]
Looks good and also makes a lot of sense to integrate this to Argent X.
Keep a local copy of the nonce and use the extended method to queue multiple transactions into one block.

@vixidev99 also notice wallets will most likely support batch execute/multicall soon.

Thanks for the contribution!

**Comment by janek26** [comment]
will get merged in #88 as it needed a rebase + merge target `develop`

**Pull request closed without merging**
